# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'UI_Estacionamento.ui'
##
## Created by: Qt User Interface Compiler version 6.5.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDateTimeEdit, QDoubleSpinBox,
    QHeaderView, QLabel, QLineEdit, QMainWindow,
    QPushButton, QSizePolicy, QSpinBox, QStatusBar,
    QTabWidget, QTableWidget, QTableWidgetItem, QTextEdit,
    QToolBar, QWidget)
import content_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(864, 600)
        icon = QIcon()
        icon.addFile(u"images/Icon_Carro.png", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QSize(16, 16))
        self.actionCadastrar_Cliente = QAction(MainWindow)
        self.actionCadastrar_Cliente.setObjectName(u"actionCadastrar_Cliente")
        icon1 = QIcon()
        icon1.addFile(u":/Img/images/Img_Cadastro.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionCadastrar_Cliente.setIcon(icon1)
        self.actionCadastrar_Funcionario = QAction(MainWindow)
        self.actionCadastrar_Funcionario.setObjectName(u"actionCadastrar_Funcionario")
        icon2 = QIcon()
        icon2.addFile(u":/Img/images/Img_CadastroFunc.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionCadastrar_Funcionario.setIcon(icon2)
        self.actionListar = QAction(MainWindow)
        self.actionListar.setObjectName(u"actionListar")
        icon3 = QIcon()
        icon3.addFile(u":/Img/images/Img_Lupa.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionListar.setIcon(icon3)
        self.actionNovo_Registro = QAction(MainWindow)
        self.actionNovo_Registro.setObjectName(u"actionNovo_Registro")
        icon4 = QIcon()
        icon4.addFile(u":/Img/images/Img_NovoRegistro.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionNovo_Registro.setIcon(icon4)
        self.actionNovo_Registro.setMenuRole(QAction.NoRole)
        self.actionAdmin = QAction(MainWindow)
        self.actionAdmin.setObjectName(u"actionAdmin")
        icon5 = QIcon()
        icon5.addFile(u":/Img/images/Img_Config.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionAdmin.setIcon(icon5)
        self.actionAdmin.setMenuRole(QAction.NoRole)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(10, 20, 651, 551))
        self.tabWidget.setStyleSheet(u"")
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(True)
        self.tabNovo_Registro = QWidget()
        self.tabNovo_Registro.setObjectName(u"tabNovo_Registro")
        self.label = QLabel(self.tabNovo_Registro)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(50, 40, 141, 16))
        font = QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.edCPF = QLineEdit(self.tabNovo_Registro)
        self.edCPF.setObjectName(u"edCPF")
        self.edCPF.setGeometry(QRect(200, 40, 181, 22))
        font1 = QFont()
        font1.setPointSize(10)
        self.edCPF.setFont(font1)
        self.label_2 = QLabel(self.tabNovo_Registro)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(50, 70, 141, 16))
        self.label_2.setFont(font)
        self.edPlaca = QLineEdit(self.tabNovo_Registro)
        self.edPlaca.setObjectName(u"edPlaca")
        self.edPlaca.setGeometry(QRect(200, 70, 181, 22))
        self.edPlaca.setFont(font1)
        self.label_3 = QLabel(self.tabNovo_Registro)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(50, 130, 141, 16))
        self.label_3.setFont(font)
        self.label_4 = QLabel(self.tabNovo_Registro)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(50, 160, 141, 16))
        self.label_4.setFont(font)
        self.dtEntrada = QDateTimeEdit(self.tabNovo_Registro)
        self.dtEntrada.setObjectName(u"dtEntrada")
        self.dtEntrada.setGeometry(QRect(200, 130, 181, 22))
        self.dtEntrada.setFont(font1)
        self.dtEntrada.setDate(QDate(2000, 1, 1))
        self.dtSaida = QDateTimeEdit(self.tabNovo_Registro)
        self.dtSaida.setObjectName(u"dtSaida")
        self.dtSaida.setGeometry(QRect(200, 160, 181, 22))
        self.dtSaida.setFont(font1)
        self.btnCriar_Reg = QPushButton(self.tabNovo_Registro)
        self.btnCriar_Reg.setObjectName(u"btnCriar_Reg")
        self.btnCriar_Reg.setGeometry(QRect(390, 350, 75, 24))
        self.btnCancelar = QPushButton(self.tabNovo_Registro)
        self.btnCancelar.setObjectName(u"btnCancelar")
        self.btnCancelar.setGeometry(QRect(490, 350, 75, 24))
        self.label_5 = QLabel(self.tabNovo_Registro)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(50, 100, 121, 18))
        self.label_5.setFont(font)
        self.cbxTipo = QComboBox(self.tabNovo_Registro)
        self.cbxTipo.addItem("")
        self.cbxTipo.addItem("")
        self.cbxTipo.setObjectName(u"cbxTipo")
        self.cbxTipo.setGeometry(QRect(200, 100, 181, 21))
        self.tabWidget.addTab(self.tabNovo_Registro, "")
        self.tabList_Reg = QWidget()
        self.tabList_Reg.setObjectName(u"tabList_Reg")
        self.twReg = QTableWidget(self.tabList_Reg)
        if (self.twReg.columnCount() < 6):
            self.twReg.setColumnCount(6)
        __qtablewidgetitem = QTableWidgetItem()
        self.twReg.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.twReg.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.twReg.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.twReg.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.twReg.setHorizontalHeaderItem(4, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.twReg.setHorizontalHeaderItem(5, __qtablewidgetitem5)
        self.twReg.setObjectName(u"twReg")
        self.twReg.setGeometry(QRect(0, 0, 601, 511))
        self.tabWidget.addTab(self.tabList_Reg, "")
        self.tabList_Func = QWidget()
        self.tabList_Func.setObjectName(u"tabList_Func")
        self.twFunc = QTableWidget(self.tabList_Func)
        if (self.twFunc.columnCount() < 7):
            self.twFunc.setColumnCount(7)
        __qtablewidgetitem6 = QTableWidgetItem()
        self.twFunc.setHorizontalHeaderItem(0, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        self.twFunc.setHorizontalHeaderItem(1, __qtablewidgetitem7)
        __qtablewidgetitem8 = QTableWidgetItem()
        self.twFunc.setHorizontalHeaderItem(2, __qtablewidgetitem8)
        __qtablewidgetitem9 = QTableWidgetItem()
        self.twFunc.setHorizontalHeaderItem(3, __qtablewidgetitem9)
        __qtablewidgetitem10 = QTableWidgetItem()
        self.twFunc.setHorizontalHeaderItem(4, __qtablewidgetitem10)
        __qtablewidgetitem11 = QTableWidgetItem()
        self.twFunc.setHorizontalHeaderItem(5, __qtablewidgetitem11)
        __qtablewidgetitem12 = QTableWidgetItem()
        self.twFunc.setHorizontalHeaderItem(6, __qtablewidgetitem12)
        self.twFunc.setObjectName(u"twFunc")
        self.twFunc.setGeometry(QRect(0, 10, 601, 501))
        self.tabWidget.addTab(self.tabList_Func, "")
        self.tabCad_Cliente = QWidget()
        self.tabCad_Cliente.setObjectName(u"tabCad_Cliente")
        self.label_6 = QLabel(self.tabCad_Cliente)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(42, 49, 49, 16))
        self.label_6.setFont(font)
        self.label_7 = QLabel(self.tabCad_Cliente)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(42, 99, 49, 16))
        self.label_7.setFont(font)
        self.label_9 = QLabel(self.tabCad_Cliente)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(42, 149, 71, 16))
        self.label_9.setFont(font)
        self.edNome_Cliente = QLineEdit(self.tabCad_Cliente)
        self.edNome_Cliente.setObjectName(u"edNome_Cliente")
        self.edNome_Cliente.setGeometry(QRect(200, 49, 171, 22))
        self.edNome_Cliente.setFont(font1)
        self.edCPF_Cli = QLineEdit(self.tabCad_Cliente)
        self.edCPF_Cli.setObjectName(u"edCPF_Cli")
        self.edCPF_Cli.setGeometry(QRect(200, 99, 171, 22))
        self.edCPF_Cli.setFont(font1)
        self.edTel_Cliente = QLineEdit(self.tabCad_Cliente)
        self.edTel_Cliente.setObjectName(u"edTel_Cliente")
        self.edTel_Cliente.setGeometry(QRect(200, 149, 171, 22))
        self.edTel_Cliente.setFont(font1)
        self.btnCad_Cli = QPushButton(self.tabCad_Cliente)
        self.btnCad_Cli.setObjectName(u"btnCad_Cli")
        self.btnCad_Cli.setGeometry(QRect(299, 320, 75, 23))
        self.btnCancelar_Cli = QPushButton(self.tabCad_Cliente)
        self.btnCancelar_Cli.setObjectName(u"btnCancelar_Cli")
        self.btnCancelar_Cli.setGeometry(QRect(389, 320, 75, 23))
        self.tabWidget.addTab(self.tabCad_Cliente, "")
        self.tabCad_Func = QWidget()
        self.tabCad_Func.setObjectName(u"tabCad_Func")
        self.edNome_Func = QLineEdit(self.tabCad_Func)
        self.edNome_Func.setObjectName(u"edNome_Func")
        self.edNome_Func.setGeometry(QRect(200, 49, 171, 22))
        self.edNome_Func.setFont(font1)
        self.edCPF_Func = QLineEdit(self.tabCad_Func)
        self.edCPF_Func.setObjectName(u"edCPF_Func")
        self.edCPF_Func.setGeometry(QRect(200, 99, 171, 22))
        self.edCPF_Func.setFont(font1)
        self.edRG_Func = QLineEdit(self.tabCad_Func)
        self.edRG_Func.setObjectName(u"edRG_Func")
        self.edRG_Func.setGeometry(QRect(200, 150, 171, 22))
        self.edRG_Func.setFont(font1)
        self.edTel_Func = QLineEdit(self.tabCad_Func)
        self.edTel_Func.setObjectName(u"edTel_Func")
        self.edTel_Func.setGeometry(QRect(200, 200, 171, 22))
        self.edTel_Func.setFont(font1)
        self.edSalario = QLineEdit(self.tabCad_Func)
        self.edSalario.setObjectName(u"edSalario")
        self.edSalario.setGeometry(QRect(200, 340, 171, 22))
        self.edSalario.setFont(font1)
        self.label_10 = QLabel(self.tabCad_Func)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(42, 49, 51, 19))
        self.label_10.setFont(font)
        self.label_11 = QLabel(self.tabCad_Func)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(42, 99, 27, 19))
        self.label_11.setFont(font)
        self.label_12 = QLabel(self.tabCad_Func)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(42, 150, 21, 19))
        self.label_12.setFont(font)
        self.label_13 = QLabel(self.tabCad_Func)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(42, 200, 71, 19))
        self.label_13.setFont(font)
        self.label_14 = QLabel(self.tabCad_Func)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(42, 340, 51, 19))
        self.label_14.setFont(font)
        self.btnCad_Func = QPushButton(self.tabCad_Func)
        self.btnCad_Func.setObjectName(u"btnCad_Func")
        self.btnCad_Func.setGeometry(QRect(320, 399, 75, 23))
        self.btnCan_Func = QPushButton(self.tabCad_Func)
        self.btnCan_Func.setObjectName(u"btnCan_Func")
        self.btnCan_Func.setGeometry(QRect(420, 399, 75, 23))
        self.label_8 = QLabel(self.tabCad_Func)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(40, 250, 81, 18))
        self.label_8.setFont(font)
        self.etEndereco = QTextEdit(self.tabCad_Func)
        self.etEndereco.setObjectName(u"etEndereco")
        self.etEndereco.setGeometry(QRect(200, 250, 171, 61))
        self.tabWidget.addTab(self.tabCad_Func, "")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.label_15 = QLabel(self.tab)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(26, 40, 118, 21))
        self.label_15.setFont(font)
        self.label_16 = QLabel(self.tab)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(26, 80, 119, 21))
        self.label_16.setFont(font)
        self.label_17 = QLabel(self.tab)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(26, 120, 65, 21))
        self.label_17.setFont(font)
        self.spbCarro = QSpinBox(self.tab)
        self.spbCarro.setObjectName(u"spbCarro")
        self.spbCarro.setGeometry(QRect(257, 41, 61, 22))
        self.spbCarro.setMaximum(9999999)
        self.spbMoto = QSpinBox(self.tab)
        self.spbMoto.setObjectName(u"spbMoto")
        self.spbMoto.setGeometry(QRect(257, 80, 61, 22))
        self.spbMoto.setMaximum(9999999)
        self.dspbDesconto = QDoubleSpinBox(self.tab)
        self.dspbDesconto.setObjectName(u"dspbDesconto")
        self.dspbDesconto.setGeometry(QRect(257, 120, 61, 22))
        self.dspbDesconto.setMaximum(1.000000000000000)
        self.dspbDesconto.setSingleStep(0.010000000000000)
        self.btnAlterar = QPushButton(self.tab)
        self.btnAlterar.setObjectName(u"btnAlterar")
        self.btnAlterar.setGeometry(QRect(246, 160, 75, 24))
        self.edReg_ID = QLineEdit(self.tab)
        self.edReg_ID.setObjectName(u"edReg_ID")
        self.edReg_ID.setGeometry(QRect(190, 240, 151, 22))
        self.label_18 = QLabel(self.tab)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(26, 240, 131, 21))
        self.label_18.setFont(font)
        self.btnDeletar = QPushButton(self.tab)
        self.btnDeletar.setObjectName(u"btnDeletar")
        self.btnDeletar.setGeometry(QRect(254, 270, 91, 24))
        self.btnRem_Func = QPushButton(self.tab)
        self.btnRem_Func.setObjectName(u"btnRem_Func")
        self.btnRem_Func.setGeometry(QRect(230, 350, 109, 24))
        self.edFunc_ID = QLineEdit(self.tab)
        self.edFunc_ID.setObjectName(u"edFunc_ID")
        self.edFunc_ID.setGeometry(QRect(190, 320, 151, 22))
        self.label_19 = QLabel(self.tab)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(30, 320, 149, 21))
        self.label_19.setFont(font)
        self.tabWidget.addTab(self.tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        self.toolBar.setIconSize(QSize(64, 64))
        self.toolBar.setToolButtonStyle(Qt.ToolButtonTextBesideIcon)
        MainWindow.addToolBar(Qt.LeftToolBarArea, self.toolBar)

        self.toolBar.addAction(self.actionCadastrar_Cliente)
        self.toolBar.addAction(self.actionCadastrar_Funcionario)
        self.toolBar.addAction(self.actionListar)
        self.toolBar.addAction(self.actionNovo_Registro)
        self.toolBar.addAction(self.actionAdmin)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Estaciona+", None))
        self.actionCadastrar_Cliente.setText(QCoreApplication.translate("MainWindow", u"Cadastrar Cliente", None))
#if QT_CONFIG(tooltip)
        self.actionCadastrar_Cliente.setToolTip(QCoreApplication.translate("MainWindow", u"Cadastrar Usu\u00e1rio", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionCadastrar_Cliente.setShortcut(QCoreApplication.translate("MainWindow", u"|", None))
#endif // QT_CONFIG(shortcut)
        self.actionCadastrar_Funcionario.setText(QCoreApplication.translate("MainWindow", u"Novo Funcion\u00e1rio", None))
#if QT_CONFIG(tooltip)
        self.actionCadastrar_Funcionario.setToolTip(QCoreApplication.translate("MainWindow", u"Cadastrar Funcion\u00e1rio", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionCadastrar_Funcionario.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+P", None))
#endif // QT_CONFIG(shortcut)
        self.actionListar.setText(QCoreApplication.translate("MainWindow", u"Listar", None))
#if QT_CONFIG(tooltip)
        self.actionListar.setToolTip(QCoreApplication.translate("MainWindow", u"Lista os registros em aberto", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionListar.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+L", None))
#endif // QT_CONFIG(shortcut)
        self.actionNovo_Registro.setText(QCoreApplication.translate("MainWindow", u"Novo Registro", None))
#if QT_CONFIG(tooltip)
        self.actionNovo_Registro.setToolTip(QCoreApplication.translate("MainWindow", u"Cria um novo registro de estacionamento", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionNovo_Registro.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.actionAdmin.setText(QCoreApplication.translate("MainWindow", u"Admin", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"CPF", None))
        self.edCPF.setInputMask(QCoreApplication.translate("MainWindow", u"999.999.999-99", None))
        self.edCPF.setText(QCoreApplication.translate("MainWindow", u"..-", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Placa", None))
        self.edPlaca.setInputMask(QCoreApplication.translate("MainWindow", u">NNN-NNNN", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Hor\u00e1rio de Entrada", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Hor\u00e1rio de Sa\u00edda", None))
        self.dtEntrada.setDisplayFormat(QCoreApplication.translate("MainWindow", u"HH:mm dd/MM/yyyy ", None))
        self.dtSaida.setDisplayFormat(QCoreApplication.translate("MainWindow", u"HH:mm dd/MM/yyyy ", None))
        self.btnCriar_Reg.setText(QCoreApplication.translate("MainWindow", u"Criar registro", None))
        self.btnCancelar.setText(QCoreApplication.translate("MainWindow", u"Cancelar", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Tipo de Ve\u00edculo", None))
        self.cbxTipo.setItemText(0, QCoreApplication.translate("MainWindow", u"Carro", None))
        self.cbxTipo.setItemText(1, QCoreApplication.translate("MainWindow", u"Moto", None))

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabNovo_Registro), QCoreApplication.translate("MainWindow", u"Novo registro", None))
        ___qtablewidgetitem = self.twReg.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"Cliente", None));
        ___qtablewidgetitem1 = self.twReg.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Nome", None));
        ___qtablewidgetitem2 = self.twReg.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"Placa", None));
        ___qtablewidgetitem3 = self.twReg.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"Horario De In\u00edcio", None));
        ___qtablewidgetitem4 = self.twReg.horizontalHeaderItem(4)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"Horario De Sa\u00edda", None));
        ___qtablewidgetitem5 = self.twReg.horizontalHeaderItem(5)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("MainWindow", u"Valor", None));
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabList_Reg), QCoreApplication.translate("MainWindow", u"Listar registros ", None))
        ___qtablewidgetitem6 = self.twFunc.horizontalHeaderItem(0)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("MainWindow", u"Identifica\u00e7\u00e3o", None));
        ___qtablewidgetitem7 = self.twFunc.horizontalHeaderItem(1)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("MainWindow", u"Nome", None));
        ___qtablewidgetitem8 = self.twFunc.horizontalHeaderItem(2)
        ___qtablewidgetitem8.setText(QCoreApplication.translate("MainWindow", u"CPF", None));
        ___qtablewidgetitem9 = self.twFunc.horizontalHeaderItem(3)
        ___qtablewidgetitem9.setText(QCoreApplication.translate("MainWindow", u"RG", None));
        ___qtablewidgetitem10 = self.twFunc.horizontalHeaderItem(4)
        ___qtablewidgetitem10.setText(QCoreApplication.translate("MainWindow", u"Telefone", None));
        ___qtablewidgetitem11 = self.twFunc.horizontalHeaderItem(5)
        ___qtablewidgetitem11.setText(QCoreApplication.translate("MainWindow", u"Endere\u00e7o", None));
        ___qtablewidgetitem12 = self.twFunc.horizontalHeaderItem(6)
        ___qtablewidgetitem12.setText(QCoreApplication.translate("MainWindow", u"Sal\u00e1rio", None));
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabList_Func), QCoreApplication.translate("MainWindow", u"Listar funcion\u00e1rios", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Nome", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"CPF", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Telefone", None))
        self.edCPF_Cli.setInputMask(QCoreApplication.translate("MainWindow", u"999.999.999-99", None))
        self.edTel_Cliente.setInputMask(QCoreApplication.translate("MainWindow", u"(9D)9999-99999", None))
        self.btnCad_Cli.setText(QCoreApplication.translate("MainWindow", u"Cadastrar", None))
        self.btnCancelar_Cli.setText(QCoreApplication.translate("MainWindow", u"Cancelar", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCad_Cliente), QCoreApplication.translate("MainWindow", u"Cadastrar cliente", None))
        self.edCPF_Func.setInputMask(QCoreApplication.translate("MainWindow", u"999.999.999-99", None))
        self.edCPF_Func.setText(QCoreApplication.translate("MainWindow", u"..-", None))
        self.edRG_Func.setInputMask(QCoreApplication.translate("MainWindow", u"99.999.999-9", None))
        self.edTel_Func.setInputMask(QCoreApplication.translate("MainWindow", u"(9D)9999-99999", None))
        self.edSalario.setInputMask("")
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Nome", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"CPF", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"RG", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Telefone", None))
#if QT_CONFIG(whatsthis)
        self.label_14.setWhatsThis(QCoreApplication.translate("MainWindow", u"Sal\u00e1rio do funcion\u00e1rio, em reais", None))
#endif // QT_CONFIG(whatsthis)
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Sal\u00e1rio", None))
        self.btnCad_Func.setText(QCoreApplication.translate("MainWindow", u"Cadastrar", None))
        self.btnCan_Func.setText(QCoreApplication.translate("MainWindow", u"Cancelar", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Endere\u00e7o", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCad_Func), QCoreApplication.translate("MainWindow", u"Cadastrar funcion\u00e1rios", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Valor para carros", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Valor para motos", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Desconto", None))
#if QT_CONFIG(whatsthis)
        self.dspbDesconto.setWhatsThis(QCoreApplication.translate("MainWindow", u"Desconto para clientes cadastrados ( em %)", None))
#endif // QT_CONFIG(whatsthis)
        self.btnAlterar.setText(QCoreApplication.translate("MainWindow", u"Alterar", None))
        self.edReg_ID.setInputMask("")
        self.edReg_ID.setPlaceholderText(QCoreApplication.translate("MainWindow", u"ID do registro", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Deletar registro", None))
        self.btnDeletar.setText(QCoreApplication.translate("MainWindow", u"Deletar Registro", None))
        self.btnRem_Func.setText(QCoreApplication.translate("MainWindow", u"Deletar funcion\u00e1rio", None))
#if QT_CONFIG(tooltip)
        self.edFunc_ID.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>ID do funcion\u00e1rio</p><p><br/></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.edFunc_ID.setInputMask("")
        self.edFunc_ID.setPlaceholderText(QCoreApplication.translate("MainWindow", u"ID do registro", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Remover Funcion\u00e1rio", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Administra\u00e7\u00e3o", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
    # retranslateUi

